# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('song', 'album')]),
        ),
    ]
