# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20161004_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Neutral')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(default='japan', max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.CharField(default='tokyo', max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
    ]
